function uniquePermissionCodes(codes: string[]): string[] {
  return Array.from(new Set(codes));
}

export const e2ePermissionSets = {
  employeeCoursesCrud: uniquePermissionCodes([
    "employee-courses.read",
    "employee-courses.create",
    "employee-courses.update",
    "employee-courses.delete",
    "employees.read",
  ]),
  employeeTalentsCrud: uniquePermissionCodes([
    "employee-talents.read",
    "employee-talents.create",
    "employee-talents.update",
    "employee-talents.delete",
    "employees.read",
    "talents.read",
  ]),
  employeePerformanceEvaluationsCrud: uniquePermissionCodes([
    "employee-performance-evaluations.read",
    "employee-performance-evaluations.create",
    "employee-performance-evaluations.update",
    "employee-performance-evaluations.delete",
    "employees.read",
    "academic-years.read",
  ]),
  employeeViolationsCrud: uniquePermissionCodes([
    "employee-violations.read",
    "employee-violations.create",
    "employee-violations.update",
    "employee-violations.delete",
    "employees.read",
  ]),
  talentsCrud: uniquePermissionCodes([
    "talents.read",
    "talents.create",
    "talents.update",
    "talents.delete",
  ]),
  academicMonthsCrud: uniquePermissionCodes([
    "academic-months.read",
    "academic-months.create",
    "academic-months.update",
    "academic-months.delete",
    "academic-years.read",
    "academic-terms.read",
  ]),
  gradingPoliciesCrud: uniquePermissionCodes([
    "grading-policies.read",
    "grading-policies.create",
    "grading-policies.update",
    "grading-policies.delete",
    "academic-years.read",
    "grade-levels.read",
    "subjects.read",
  ]),
  gradingReportsRead: uniquePermissionCodes([
    "grading-reports.read",
    "academic-years.read",
    "grade-levels.read",
    "sections.read",
    "academic-terms.read",
  ]),
  hrReportsRead: uniquePermissionCodes([
    "hr-reports.read",
    "employees.read",
  ]),
  employeeTasksCrud: uniquePermissionCodes([
    "employee-tasks.read",
    "employee-tasks.create",
    "employee-tasks.update",
    "employee-tasks.delete",
    "employees.read",
    "academic-years.read",
  ]),
  termSubjectOfferingsCrud: uniquePermissionCodes([
    "term-subject-offerings.read",
    "term-subject-offerings.create",
    "term-subject-offerings.update",
    "term-subject-offerings.delete",
    "academic-years.read",
    "academic-terms.read",
    "grade-level-subjects.read",
  ]),
  systemSettingsCrud: uniquePermissionCodes([
    "system-settings.read",
    "system-settings.create",
    "system-settings.update",
    "system-settings.delete",
  ]),
  remindersTickerCrud: uniquePermissionCodes([
    "reminders-ticker.read",
    "reminders-ticker.create",
    "reminders-ticker.update",
    "reminders-ticker.delete",
  ]),
  userPermissionsCrud: uniquePermissionCodes([
    "user-permissions.read",
    "user-permissions.create",
    "user-permissions.update",
    "user-permissions.delete",
    "user-permissions.revoke",
    "users.read",
    "permissions.read",
  ]),
  employeeSectionSupervisionsCrud: uniquePermissionCodes([
    "employee-section-supervisions.read",
    "employee-section-supervisions.create",
    "employee-section-supervisions.update",
    "employee-section-supervisions.delete",
    "employees.read",
    "sections.read",
    "academic-years.read",
  ]),
  lookupBloodTypesCrud: uniquePermissionCodes([
    "lookup-blood-types.read",
    "lookup-blood-types.create",
    "lookup-blood-types.update",
    "lookup-blood-types.delete",
  ]),
  lookupIdTypesCrud: uniquePermissionCodes([
    "lookup-id-types.read",
    "lookup-id-types.create",
    "lookup-id-types.update",
    "lookup-id-types.delete",
  ]),
  lookupOwnershipTypesCrud: uniquePermissionCodes([
    "lookup-ownership-types.read",
    "lookup-ownership-types.create",
    "lookup-ownership-types.update",
    "lookup-ownership-types.delete",
  ]),
  lookupPeriodsCrud: uniquePermissionCodes([
    "lookup-periods.read",
    "lookup-periods.create",
    "lookup-periods.update",
    "lookup-periods.delete",
  ]),
  lookupAbilityLevelsCrud: uniquePermissionCodes([
    "lookup-ability-levels.read",
    "lookup-ability-levels.create",
    "lookup-ability-levels.update",
    "lookup-ability-levels.delete",
  ]),
  lookupActivityTypesCrud: uniquePermissionCodes([
    "lookup-activity-types.read",
    "lookup-activity-types.create",
    "lookup-activity-types.update",
    "lookup-activity-types.delete",
  ]),
  lookupEnrollmentStatusesCrud: uniquePermissionCodes([
    "lookup-enrollment-statuses.read",
    "lookup-enrollment-statuses.create",
    "lookup-enrollment-statuses.update",
    "lookup-enrollment-statuses.delete",
  ]),
  lookupOrphanStatusesCrud: uniquePermissionCodes([
    "lookup-orphan-statuses.read",
    "lookup-orphan-statuses.create",
    "lookup-orphan-statuses.update",
    "lookup-orphan-statuses.delete",
  ]),
  lookupCatalogIndexSampleRead: uniquePermissionCodes([
    "lookup-blood-types.read",
    "lookup-enrollment-statuses.read",
  ]),
  lookupCatalogIdTypesReadCreate: uniquePermissionCodes([
    "lookup-id-types.read",
    "lookup-id-types.create",
  ]),
  studentTalentsCrud: uniquePermissionCodes([
    "student-talents.read",
    "student-talents.create",
    "student-talents.update",
    "student-talents.delete",
    "students.read",
    "talents.read",
  ]),
  studentSiblingsCrud: uniquePermissionCodes([
    "student-siblings.read",
    "student-siblings.create",
    "student-siblings.update",
    "student-siblings.delete",
    "students.read",
  ]),
  studentProblemsCrud: uniquePermissionCodes([
    "student-problems.read",
    "student-problems.create",
    "student-problems.update",
    "student-problems.delete",
    "students.read",
  ]),
  parentNotificationsCrud: uniquePermissionCodes([
    "parent-notifications.read",
    "parent-notifications.create",
    "parent-notifications.update",
    "parent-notifications.delete",
    "students.read",
    "lookup-catalog.read",
  ]),
} as const;

export const defaultE2ePermissionCodes = uniquePermissionCodes([
  ...e2ePermissionSets.employeePerformanceEvaluationsCrud,
  ...e2ePermissionSets.employeeViolationsCrud,
  ...e2ePermissionSets.talentsCrud,
  ...e2ePermissionSets.academicMonthsCrud,
  ...e2ePermissionSets.gradingPoliciesCrud,
  ...e2ePermissionSets.gradingReportsRead,
  ...e2ePermissionSets.hrReportsRead,
  ...e2ePermissionSets.employeeTasksCrud,
  ...e2ePermissionSets.termSubjectOfferingsCrud,
  ...e2ePermissionSets.systemSettingsCrud,
  ...e2ePermissionSets.remindersTickerCrud,
  ...e2ePermissionSets.userPermissionsCrud,
  ...e2ePermissionSets.employeeSectionSupervisionsCrud,
  ...e2ePermissionSets.lookupBloodTypesCrud,
  ...e2ePermissionSets.lookupIdTypesCrud,
  ...e2ePermissionSets.lookupOwnershipTypesCrud,
  ...e2ePermissionSets.lookupPeriodsCrud,
  ...e2ePermissionSets.lookupAbilityLevelsCrud,
  ...e2ePermissionSets.lookupActivityTypesCrud,
  ...e2ePermissionSets.lookupEnrollmentStatusesCrud,
  ...e2ePermissionSets.lookupOrphanStatusesCrud,
  ...e2ePermissionSets.studentTalentsCrud,
  ...e2ePermissionSets.studentSiblingsCrud,
  ...e2ePermissionSets.studentProblemsCrud,
  ...e2ePermissionSets.parentNotificationsCrud,
]);
