import {
  AlertTriangle,
  BellRing,
  BookOpenText,
  BookText,
  Briefcase,
  Building,
  Cable,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Coins,
  ClipboardCheck,
  ClipboardList,
  Gauge,
  GraduationCap,
  KeyRound,
  Layers3,
  Medal,
  Shuffle,
  ScrollText,
  Settings2,
  ShieldCheck,
  HeartPulse,
  Sparkles,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { PermissionRequirement } from "@/features/auth/lib";

export type AppNavItem = PermissionRequirement & {
  href: string;
  label: string;
  icon: LucideIcon;
  iconClassName?: string;
};

export type AppNavGroup = {
  id: string;
  label: string;
  icon: LucideIcon;
  iconClassName?: string;
  surfaceClassName?: string;
  items: AppNavItem[];
};

export const APP_NAV_GROUPS: AppNavGroup[] = [
  {
    id: "overview",
    label: "عام",
    icon: Gauge,
    iconClassName: "border-slate-500/20 bg-slate-500/10 text-slate-700 dark:text-slate-300",
    surfaceClassName: "bg-gradient-to-l from-slate-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app",
        label: "لوحة التحكم",
        icon: Gauge,
      },
    ],
  },
  {
    id: "system-01-shared",
    label: "البنية المشتركة",
    icon: ShieldCheck,
    iconClassName: "border-violet-500/20 bg-violet-500/10 text-violet-700 dark:text-violet-300",
    surfaceClassName: "bg-gradient-to-l from-violet-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/users",
        label: "المستخدمون",
        icon: Users,
        requiredPermission: "users.read",
      },
      {
        href: "/app/roles",
        label: "الأدوار",
        icon: ShieldCheck,
        requiredPermission: "roles.read",
      },
      {
        href: "/app/permissions",
        label: "الصلاحيات",
        icon: KeyRound,
        requiredPermission: "permissions.read",
      },
      {
        href: "/app/audit-logs",
        label: "سجل التدقيق",
        icon: ScrollText,
        requiredPermission: "audit-logs.read",
      },
      {
        href: "/app/global-settings",
        label: "الإعدادات العامة",
        icon: Settings2,
        requiredPermission: "global-settings.read",
      },
      {
        href: "/app/system-settings",
        label: "إعدادات النظام",
        icon: Settings2,
        requiredPermission: "system-settings.read",
      },
      {
        href: "/app/reminders-ticker",
        label: "شريط التنبيهات",
        icon: ScrollText,
        requiredPermission: "reminders-ticker.read",
      },
      {
        href: "/app/user-notifications",
        label: "إشعاراتي",
        icon: BellRing,
        requiredPermission: "user-notifications.read",
      },
      {
        href: "/app/user-permissions",
        label: "صلاحيات مباشرة",
        icon: KeyRound,
        requiredPermission: "user-permissions.read",
      },
      {
        href: "/app/school-profiles",
        label: "ملف المدرسة",
        icon: Building,
        requiredPermission: "school-profiles.read",
      },
      {
        href: "/app/lookup-catalog",
        label: "قاموس كل المرجعيات",
        icon: Layers3,
        requiredPermission: "lookup-catalog.read",
        iconClassName: "border-fuchsia-500/20 bg-fuchsia-500/10 text-fuchsia-700 dark:text-fuchsia-300",
      },
    ],
  },
  {
    id: "system-02-academic-core",
    label: "النواة الأكاديمية",
    icon: CalendarDays,
    iconClassName: "border-emerald-500/20 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300",
    surfaceClassName: "bg-gradient-to-l from-emerald-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/academic-years",
        label: "السنوات الأكاديمية",
        icon: CalendarDays,
        requiredPermission: "academic-years.read",
      },
      {
        href: "/app/academic-terms",
        label: "الفصول الأكاديمية",
        icon: CalendarRange,
        requiredPermission: "academic-terms.read",
      },
      {
        href: "/app/academic-months",
        label: "الأشهر الأكاديمية",
        icon: CalendarClock,
        requiredPermission: "academic-months.read",
      },
      {
        href: "/app/grade-levels",
        label: "المراحل/الصفوف",
        icon: Layers3,
        requiredPermission: "grade-levels.read",
      },
      {
        href: "/app/subjects",
        label: "المواد الدراسية",
        icon: BookOpenText,
        requiredPermission: "subjects.read",
      },
      {
        href: "/app/sections",
        label: "الشعب الدراسية",
        icon: Layers3,
        requiredPermission: "sections.read",
      },
      {
        href: "/app/classrooms",
        label: "الفصول / الغرف",
        icon: Building,
        requiredPermission: "classrooms.read",
        iconClassName: "border-amber-500/20 bg-amber-500/10 text-amber-700 dark:text-amber-300",
      },
      {
        href: "/app/section-classroom-assignments",
        label: "ربط الشعب بالغرف",
        icon: Cable,
        requiredPermission: "sections.read",
        iconClassName: "border-teal-500/20 bg-teal-500/10 text-teal-700 dark:text-teal-300",
      },
      {
        href: "/app/grade-level-subjects",
        label: "ربط الصفوف بالمواد",
        icon: Cable,
        requiredPermission: "grade-level-subjects.read",
      },
      {
        href: "/app/term-subject-offerings",
        label: "عروض المواد للفصول",
        icon: Cable,
        requiredPermission: "term-subject-offerings.read",
      },
      {
        href: "/app/timetable-entries",
        label: "الجدول الدراسي",
        icon: CalendarClock,
        requiredPermission: "timetable-entries.read",
      },
    ],
  },
  {
    id: "system-03-hr",
    label: "الموارد البشرية",
    icon: Users,
    iconClassName: "border-sky-500/20 bg-sky-500/10 text-sky-700 dark:text-sky-300",
    surfaceClassName: "bg-gradient-to-l from-sky-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/employees",
        label: "الموظفون",
        icon: Users,
        requiredPermission: "employees.read",
      },
      {
        href: "/app/employee-teaching-assignments",
        label: "إسناد التدريس",
        icon: Cable,
        requiredPermission: "employee-teaching-assignments.read",
      },
      {
        href: "/app/employee-section-supervisions",
        label: "نطاقات الإشراف",
        icon: Cable,
        requiredPermission: "employee-section-supervisions.read",
      },
      {
        href: "/app/employee-attendance",
        label: "حضور الموظفين",
        icon: ClipboardCheck,
        requiredPermission: "employee-attendance.read",
      },
      {
        href: "/app/employee-tasks",
        label: "مهام الموظفين",
        icon: ClipboardList,
        requiredPermission: "employee-tasks.read",
      },
      {
        href: "/app/employee-contracts",
        label: "عقود الموظفين",
        icon: ScrollText,
        requiredPermission: "employee-contracts.read",
      },
      {
        href: "/app/employee-departments",
        label: "أقسام الموظفين",
        icon: Briefcase,
        requiredPermission: "employee-departments.read",
      },
      {
        href: "/app/employee-documents",
        label: "مستندات الموظفين",
        icon: BookOpenText,
        requiredPermission: "employee-documents.read",
      },
      {
        href: "/app/employee-leaves",
        label: "طلبات الإجازات",
        icon: CalendarRange,
        requiredPermission: "employee-leaves.read",
      },
      {
        href: "/app/employee-leave-balances",
        label: "أرصدة الإجازات",
        icon: CalendarDays,
        requiredPermission: "employee-leave-balances.read",
      },
      {
        href: "/app/employee-courses",
        label: "دورات الموظفين",
        icon: BookText,
        requiredPermission: "employee-courses.read",
      },
      {
        href: "/app/employee-lifecycle-checklists",
        label: "التهيئة وإنهاء الخدمة",
        icon: ClipboardList,
        requiredPermission: "employee-lifecycle-checklists.read",
      },
      {
        href: "/app/talents",
        label: "قاموس المواهب",
        icon: Sparkles,
        requiredPermission: "talents.read",
      },
      {
        href: "/app/employee-talents",
        label: "مواهب الموظفين",
        icon: Sparkles,
        requiredPermission: "employee-talents.read",
      },
      {
        href: "/app/employee-performance-evaluations",
        label: "تقييمات الأداء",
        icon: Medal,
        requiredPermission: "employee-performance-evaluations.read",
      },
      {
        href: "/app/employee-violations",
        label: "مخالفات الموظفين",
        icon: AlertTriangle,
        requiredPermission: "employee-violations.read",
      },
      {
        href: "/app/hr-reports",
        label: "تقارير الموارد البشرية",
        icon: ScrollText,
        requiredPermission: "hr-reports.read",
      },
    ],
  },
  {
    id: "system-04-students",
    label: "الطلاب",
    icon: GraduationCap,
    iconClassName: "border-indigo-500/20 bg-indigo-500/10 text-indigo-700 dark:text-indigo-300",
    surfaceClassName: "bg-gradient-to-l from-indigo-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/students",
        label: "الطلاب",
        icon: GraduationCap,
        requiredAnyPermission: ["students.read.summary"],
      },
      {
        href: "/app/guardians",
        label: "أولياء الأمور",
        icon: Users,
        requiredAnyPermission: ["guardians.read.summary", "guardians.read"],
      },
      {
        href: "/app/student-guardians",
        label: "ربط الطالب وولي الأمر",
        icon: Cable,
        requiredPermission: "student-guardians.read",
      },
      {
        href: "/app/student-enrollments",
        label: "قيود الطلاب",
        icon: ClipboardList,
        requiredAnyPermission: ["student-enrollments.read.summary", "student-enrollments.read"],
      },
      {
        href: "/app/student-distributions",
        label: "توزيع الطلاب على الشعب",
        icon: Shuffle,
        requiredAnyPermission: ["student-enrollments.read.summary", "student-enrollments.read"],
      },
      {
        href: "/app/student-attendance",
        label: "حضور الطلاب",
        icon: ClipboardCheck,
        requiredPermission: "student-attendance.read",
      },
      {
        href: "/app/student-books",
        label: "كتب الطلاب",
        icon: BookText,
        requiredPermission: "student-books.read",
      },
      {
        href: "/app/student-talents",
        label: "مواهب الطلاب",
        icon: Sparkles,
        requiredPermission: "student-talents.read",
      },
      {
        href: "/app/student-siblings",
        label: "الإخوة في المدرسة",
        icon: Users,
        requiredPermission: "student-siblings.read",
      },
      {
        href: "/app/student-problems",
        label: "مشكلات الطلاب",
        icon: AlertTriangle,
        requiredPermission: "student-problems.read",
      },
      {
        href: "/app/parent-notifications",
        label: "إشعارات أولياء الأمور",
        icon: ScrollText,
        requiredPermission: "parent-notifications.read",
      },
    ],
  },
  {
    id: "system-05-grades-calendar",
    label: "التعليم والدرجات - التقويم",
    icon: CalendarRange,
    iconClassName: "border-cyan-500/20 bg-cyan-500/10 text-cyan-700 dark:text-cyan-300",
    surfaceClassName: "bg-gradient-to-l from-cyan-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/academic-terms",
        label: "الفصول الأكاديمية",
        icon: CalendarRange,
        requiredPermission: "academic-terms.read",
      },
      {
        href: "/app/academic-months",
        label: "الأشهر الأكاديمية",
        icon: CalendarClock,
        requiredPermission: "academic-months.read",
      },
    ],
  },
  {
    id: "system-05-grades-setup",
    label: "التعليم والدرجات - الإعدادات",
    icon: Medal,
    iconClassName: "border-orange-500/20 bg-orange-500/10 text-orange-700 dark:text-orange-300",
    surfaceClassName: "bg-gradient-to-l from-orange-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/lookup-grade-descriptions",
        label: "أوصاف التقديرات",
        icon: Medal,
        requiredPermission: "lookup-grade-descriptions.read",
      },
      {
        href: "/app/annual-statuses",
        label: "الحالات السنوية",
        icon: Medal,
        requiredPermission: "annual-statuses.read",
      },
      {
        href: "/app/promotion-decisions",
        label: "قرارات الترفيع",
        icon: Medal,
        requiredPermission: "promotion-decisions.read",
      },
      {
        href: "/app/grading-outcome-rules",
        label: "قواعد النتائج",
        icon: Medal,
        requiredPermission: "grading-outcome-rules.read",
      },
      {
        href: "/app/grading-policies",
        label: "سياسات التقييم والدرجات",
        icon: Medal,
        requiredPermission: "grading-policies.read",
      },
      {
        href: "/app/grading-policy-components",
        label: "مكوّنات سياسات التقييم",
        icon: Medal,
        requiredPermission: "grading-policy-components.read",
      },
    ],
  },
  {
    id: "system-05-assignments",
    label: "التعليم والدرجات - نظام الواجبات",
    icon: ClipboardCheck,
    iconClassName: "border-emerald-500/20 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300",
    surfaceClassName: "bg-gradient-to-l from-emerald-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/homework-types",
        label: "أنواع الواجبات",
        icon: BookOpenText,
        requiredPermission: "homework-types.read",
      },
      {
        href: "/app/homeworks",
        label: "الواجبات",
        icon: ClipboardList,
        requiredPermission: "homeworks.read",
      },
      {
        href: "/app/student-homeworks",
        label: "واجبات الطلاب",
        icon: ClipboardCheck,
        requiredPermission: "student-homeworks.read",
      },
    ],
  },
  {
    id: "system-05-attendance",
    label: "التعليم والدرجات - حضور الطلاب",
    icon: ClipboardCheck,
    iconClassName: "border-cyan-500/20 bg-cyan-500/10 text-cyan-700 dark:text-cyan-300",
    surfaceClassName: "bg-gradient-to-l from-cyan-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/student-attendance",
        label: "حضور وغياب الطلاب",
        icon: ClipboardCheck,
        requiredPermission: "student-attendance.read",
      },
    ],
  },
  {
    id: "system-05-exams",
    label: "التعليم والدرجات - نظام الاختبارات",
    icon: ClipboardCheck,
    iconClassName: "border-violet-500/20 bg-violet-500/10 text-violet-700 dark:text-violet-300",
    surfaceClassName: "bg-gradient-to-l from-violet-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/exam-periods",
        label: "الفترات الاختبارية",
        icon: CalendarClock,
        requiredPermission: "exam-periods.read",
      },
      {
        href: "/app/exam-assessments",
        label: "التقييمات والاختبارات",
        icon: ClipboardList,
        requiredPermission: "exam-assessments.read",
      },
      {
        href: "/app/student-exam-scores",
        label: "درجات الاختبارات",
        icon: ClipboardCheck,
        requiredPermission: "student-exam-scores.read",
      },
    ],
  },
  {
    id: "system-05-monthly-periods",
    label: "التعليم والدرجات - الفترات الشهرية",
    icon: Medal,
    iconClassName: "border-amber-500/20 bg-amber-500/10 text-amber-700 dark:text-amber-300",
    surfaceClassName: "bg-gradient-to-l from-amber-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/monthly-assessment-periods",
        label: "الفترات الشهرية",
        icon: Medal,
        requiredPermission: "assessment-periods.read",
      },
      {
        href: "/app/monthly-assessment-components",
        label: "مكونات الفترات الشهرية",
        icon: Medal,
        requiredPermission: "assessment-period-components.read",
      },
      {
        href: "/app/monthly-component-links",
        label: "ربط مكونات الشهر",
        icon: Medal,
        requiredPermission: "assessment-period-components.read",
      },
      {
        href: "/app/monthly-period-results",
        label: "نتائج الفترات الشهرية",
        icon: Medal,
        requiredPermission: "student-period-results.read",
      },
      {
        href: "/app/monthly-period-component-scores",
        label: "درجات مكونات الشهر",
        icon: Medal,
        requiredPermission: "student-period-component-scores.read",
      },
      {
        href: "/app/monthly-period-bulk-entry",
        label: "الإدخال الجماعي الشهري",
        icon: Medal,
        requiredPermission: "student-period-component-scores.create",
      },
    ],
  },
  {
    id: "system-05-semester-periods",
    label: "التعليم والدرجات - الفترات الفصلية",
    icon: Medal,
    iconClassName: "border-rose-500/20 bg-rose-500/10 text-rose-700 dark:text-rose-300",
    surfaceClassName: "bg-gradient-to-l from-rose-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/semester-assessment-periods",
        label: "الفترات الفصلية",
        icon: Medal,
        requiredPermission: "assessment-periods.read",
      },
      {
        href: "/app/semester-assessment-components",
        label: "مكونات الفترات الفصلية",
        icon: Medal,
        requiredPermission: "assessment-period-components.read",
      },
      {
        href: "/app/semester-aggregate-links",
        label: "فترات المحصلة للفصل",
        icon: Medal,
        requiredPermission: "assessment-component-source-periods.read",
      },
      {
        href: "/app/semester-period-results",
        label: "نتائج الفترات الفصلية",
        icon: Medal,
        requiredPermission: "student-period-results.read",
      },
      {
        href: "/app/semester-period-component-scores",
        label: "درجات مكونات الفصل",
        icon: Medal,
        requiredPermission: "student-period-component-scores.read",
      },
      {
        href: "/app/semester-period-calculation",
        label: "احتساب الفترات الفصلية",
        icon: Medal,
        requiredPermission: "student-period-results.calculate",
      },
    ],
  },
  {
    id: "system-05-year-final-periods",
    label: "التعليم والدرجات - الفترات النهائية",
    icon: Medal,
    iconClassName: "border-sky-500/20 bg-sky-500/10 text-sky-700 dark:text-sky-300",
    surfaceClassName: "bg-gradient-to-l from-sky-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/year-final-assessment-periods",
        label: "الفترات النهائية",
        icon: Medal,
        requiredPermission: "assessment-periods.read",
      },
      {
        href: "/app/year-final-assessment-components",
        label: "مكونات الفترات النهائية",
        icon: Medal,
        requiredPermission: "assessment-period-components.read",
      },
      {
        href: "/app/year-final-source-links",
        label: "مصادر الفترات النهائية",
        icon: Medal,
        requiredPermission: "assessment-component-source-periods.read",
      },
      {
        href: "/app/year-final-period-results",
        label: "النتائج النهائية",
        icon: Medal,
        requiredPermission: "student-period-results.read",
      },
    ],
  },
  {
    id: "system-05-grades-results",
    label: "التعليم والدرجات - النتائج",
    icon: ScrollText,
    iconClassName: "border-fuchsia-500/20 bg-fuchsia-500/10 text-fuchsia-700 dark:text-fuchsia-300",
    surfaceClassName: "bg-gradient-to-l from-fuchsia-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/annual-results",
        label: "النتائج السنوية والقرار النهائي",
        icon: Medal,
        requiredPermission: "annual-results.read",
      },
      {
        href: "/app/grading-reports",
        label: "تقارير الدرجات",
        icon: ScrollText,
        requiredPermission: "grading-reports.read",
      },
    ],
  },
  {
    id: "system-07-finance",
    label: "المالية",
    icon: Coins,
    iconClassName: "border-emerald-500/20 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300",
    surfaceClassName: "bg-gradient-to-l from-emerald-500/10 via-transparent to-transparent",
    items: [
      {
        href: "/app/finance",
        label: "النظام المالي",
        icon: Coins,
        iconClassName:
          "border-emerald-500/20 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300",
      },
      {
        href: "/app/branches",
        label: "الفروع",
        icon: Building,
        requiredPermission: "branches.read",
      },
      {
        href: "/app/currencies",
        label: "العملات",
        icon: Coins,
        requiredPermission: "currencies.read",
      },
      {
        href: "/app/currency-exchange-rates",
        label: "أسعار الصرف",
        icon: Shuffle,
        requiredPermission: "currency-exchange-rates.read",
      },
      {
        href: "/app/fiscal-years",
        label: "السنوات المالية",
        icon: CalendarDays,
        requiredPermission: "fiscal-years.read",
      },
      {
        href: "/app/fiscal-periods",
        label: "الفترات المالية",
        icon: CalendarRange,
        requiredPermission: "fiscal-periods.read",
      },
      {
        href: "/app/chart-of-accounts",
        label: "دليل الحسابات",
        icon: Layers3,
        requiredPermission: "chart-of-accounts.read",
      },
      {
        href: "/app/cost-centers",
        label: "مراكز التكلفة",
        icon: Layers3,
        requiredPermission: "cost-centers.read",
      },
      {
        href: "/app/tax-configurations",
        label: "إعدادات الضرائب",
        icon: Settings2,
        requiredPermission: "tax-configurations.read",
      },
      {
        href: "/app/fee-structures",
        label: "هياكل الرسوم",
        icon: BookText,
        requiredPermission: "fee-structures.read",
      },
      {
        href: "/app/discount-rules",
        label: "قواعد الخصم",
        icon: Medal,
        requiredPermission: "discount-rules.read",
      },
      {
        href: "/app/student-invoices",
        label: "فواتير الطلاب",
        icon: ClipboardList,
        requiredPermission: "student-invoices.read",
      },
      {
        href: "/app/invoice-installments",
        label: "أقساط الفواتير",
        icon: CalendarClock,
        requiredPermission: "invoice-installments.read",
      },
      {
        href: "/app/billing-engine",
        label: "محرك الفوترة",
        icon: Gauge,
        requiredPermission: "billing.read-statement",
      },
      {
        href: "/app/hr-integrations",
        label: "تكاملات الموارد البشرية",
        icon: Users,
        requiredAnyPermission: [
          "finance-hr.payroll-summary",
          "finance-hr.payroll-journal",
          "finance-hr.deduction-journal",
        ],
      },
      {
        href: "/app/procurement-integrations",
        label: "تكاملات المشتريات",
        icon: ClipboardCheck,
        requiredPermission: "finance-procurement.purchase-journal",
      },
      {
        href: "/app/transport-integrations",
        label: "تكاملات النقل",
        icon: Cable,
        requiredPermission: "finance-transport.generate-invoices",
      },
      {
        href: "/app/journal-entries",
        label: "القيود اليومية",
        icon: ClipboardList,
        requiredPermission: "journal-entries.read",
      },
      {
        href: "/app/payment-gateways",
        label: "بوابات الدفع",
        icon: Cable,
        requiredPermission: "payment-gateways.read",
      },
      {
        href: "/app/payment-transactions",
        label: "عمليات الدفع",
        icon: Coins,
        requiredPermission: "payment-transactions.read",
      },
      {
        href: "/app/bank-reconciliations",
        label: "التسويات البنكية",
        icon: ScrollText,
        requiredPermission: "bank-reconciliations.read",
      },
      {
        href: "/app/credit-debit-notes",
        label: "إشعارات خصم/إضافة",
        icon: AlertTriangle,
        requiredPermission: "credit-debit-notes.read",
      },
      {
        href: "/app/recurring-journals",
        label: "القيود الدورية",
        icon: CalendarClock,
        requiredPermission: "recurring-journals.read",
      },
      {
        href: "/app/budgets",
        label: "الميزانيات",
        icon: ClipboardCheck,
        requiredPermission: "budgets.read",
      },
      {
        href: "/app/financial-funds",
        label: "الصناديق المالية",
        icon: Coins,
        requiredPermission: "financial-funds.read",
      },
      {
        href: "/app/financial-categories",
        label: "الفئات المالية",
        icon: Layers3,
        requiredPermission: "financial-categories.read",
      },
      {
        href: "/app/revenues",
        label: "الإيرادات",
        icon: Coins,
        requiredPermission: "revenues.read",
      },
      {
        href: "/app/expenses",
        label: "المصروفات",
        icon: AlertTriangle,
        requiredPermission: "expenses.read",
      },
      {
        href: "/app/community-contributions",
        label: "المساهمات المجتمعية",
        icon: Sparkles,
        requiredPermission: "community-contributions.read",
      },
      {
        href: "/app/financial-reports",
        label: "التقارير المالية",
        icon: ScrollText,
        requiredPermission: "financial-reports.read",
      },
      {
        href: "/app/audit-trail",
        label: "سجل الأثر المالي",
        icon: ScrollText,
        requiredPermission: "audit-trail.read",
      },
    ],
  },
  {
    id: "system-19-health",
    label: "النظام 19 - الصحة المدرسية",
    icon: HeartPulse,
    items: [
      {
        href: "/app/health",
        label: "نظام الصحة",
        icon: HeartPulse,
        requiredPermission: "health-visits.read",
      },
    ],
  },
];

export const APP_NAV_ITEMS: AppNavItem[] = APP_NAV_GROUPS.flatMap(
  (group) => group.items,
);



